version: '3.8'

services:
    app:
        build:
            context: .
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"
        networks:
            - laravel

    db:
        image: postgres:13
        container_name: postgres_db
        environment:
            POSTGRES_DB: shopmaster_db
            POSTGRES_USER: laravel_user
            POSTGRES_PASSWORD: secret
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - laravel
        ports:
            - "5432:5432"

volumes:
    db-data:

networks:
    laravel:
